### ISSUE TITLE
RDAP Extension Versioning section

### ISSUE THREAD

**Issue by jasdips** [anewton1998/draft-regext-ext-json-media-type#15]
Wonder if we should remove this section since we are implying a design (albeit caveated as not a full-fledged design) here, especially vis-a-vis the IANA registry for RDAP extensions, and while the semantic versioning discussion is ongoing? It could potentially be distracting from the core concept (new RDAP With Extensions media type).

Though good to somewhere else retain the "the new media type defined in this document has utility with existing, opaquely versioned RDAP extensions and does not depend on the definition of a new versioning scheme for RDAP extensions" point.

**Comment by anewton1998** [comment]
For now, I believe we should keep it as it is a point we are trying to make to the working group. If it comes to the point of IETF RFC publication, we'll probably need to remove it.

**Comment by jasdips** [comment]
Ok.
