### ISSUE TITLE
Change from rdapx to rdap-x

### ISSUE THREAD

**Issue by anewton1998** [anewton1998/draft-regext-ext-json-media-type#18]
Visually, the 'x' seems to get a little lost. Checking the ABNF of media types, a '-' is allowed. Therefore I'd like to change from `rdax` to `rdap-x`.

Additionally, where the document refers to `RDAP With Extensions`, I'd like to shorten that to `RDAP-X`.

**Comment by jasdips** [comment]
Agree with both.

**Comment by jasdips** [comment]
There are few other places where it is still rdapx.

**Comment by anewton1998** [comment]
Will fix in next PR.
