### ISSUE TITLE
Unsupported extension

### ISSUE THREAD

**Issue by jasdips** [anewton1998/draft-regext-ext-json-media-type#21]
Say an extension has gone through 3 iterations with "extv1", "extv2", and "extv3" ids registered with IANA. A client when querying sends "extv1" in the Accept header but the server by then only supports "extv2" and "extv3" with "extv1" sunset. Should the server return a 501 (Not Implemented) with the Content-Type header containing "extv2" and "extv3"? Might be good to cover such a scenario in the doc.

**Comment by anewton1998** [comment]
Wouldn't 406 be better than 501? https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406

I'll address this in the next PR.

**Comment by jasdips** [comment]
Yes, 406 is perfect here.

**Comment by jasdips** [comment]
So, if responding with a 406 Not Acceptable is NOT RECOMMENDED and the client is supposed to ignore unknown extensions ("extv3"), would the server still respond back with say "extv3" JSON (along with the Content-Type header containing "extv3") as part of the response, or not return any JSON for that extension?

**Comment by anewton1998** [comment]
It should be the same behavior as today. The server returns whichever extensions it desires. The same applies for extensions the client didn't request. If the client asks for "foo" and the server only wants to return "bar", then "bar" is what the client gets.

**Comment by jasdips** [comment]
Cool beans.
